name: connection_plugin
description: "A new Flutter plugin chek connection"
version: 0.0.1
homepage: https://github.com/Saifulkamil/connection_plugin.git

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 
flutter:
 
  plugin:
    platforms:
      android:
        package: com.example.connection_plugin
        pluginClass: ConnectionPlugin
 